/* ------------------------------------------------------------------ *
 * Copying the delivery photographs somewhere Jesse controls.
 *
 * Condition 9. Supabase's own documentation, verbatim: "Database backups do
 * not include objects you store via the Storage API." The signed record
 * survives in Postgres and the image does not, and the image is the thing
 * that settles a retailer dispute.
 *
 * PURE ON PURPOSE. Nothing here opens a database connection, reads an
 * environment variable or makes a network call. Every one of those arrives
 * as a dependency, so the whole of the logic below can be asserted in a
 * script against fakes -- including the failure paths, which are the ones
 * that matter and the ones nobody ever exercises by hand.
 *
 * That is also why there is no `server-only` guard on this file and there is
 * one on lib/backup/transport.ts. Nothing here touches a secret, so the
 * checks can run in CI with no credentials and no network at all.
 *
 * WHY ONE FAILED OBJECT DOES NOT STOP THE RUN
 *
 * This is the opposite rule to lib/xero-invoice.ts, deliberately, and the
 * difference is worth stating because the two files sit in the same codebase
 * saying opposite things.
 *
 * An invoice that bills Monday and Wednesday but not Friday has quietly
 * under-billed a customer and nothing on it says so. Partial is WORSE than
 * nothing, so a refusal anywhere stops the whole week.
 *
 * A backup that copies nine photographs out of ten has saved nine
 * photographs. Partial is BETTER than nothing. So a failure is recorded, the
 * run is marked failed so the alarm still goes off, and the other nine still
 * get copied -- and because the next run picks up whatever has no
 * backup_objects row, the tenth is retried on Monday without anyone doing
 * anything.
 *
 * WHY THERE IS A LIMIT AT ALL
 *
 * Netlify's platform maximum for a synchronous function is 60 seconds and
 * this runs inside one. At 56 kB an object the network is not the
 * constraint, but a first run against a year of accumulated photographs
 * would be, so it takes a bounded bite and the schedule catches up. A run
 * that hits its limit is a normal successful run, not a failure -- reporting
 * it as failed would train everyone to ignore the alarm.
 * ------------------------------------------------------------------ */

export type SourceObject = {
  /** The path in OUR storage, e.g. "2026-09-04/<delivery>/photo-<id>.jpg". */
  storagePath: string;
  sha256: string;
};

export type BackupTransport = {
  /** Recorded on every row, so the history says which objects went where. */
  name: string;
  put(remotePath: string, bytes: Uint8Array, contentType: string): Promise<void>;
};

export type UploadedRow = {
  storagePath: string;
  sha256: string;
  bytes: number;
  remotePath: string;
  destination: string;
};

export type SyncDeps = {
  transport: BackupTransport;
  /** Objects with no backup_objects row, or whose sha256 no longer matches. */
  listPending(limit: number): Promise<SourceObject[]>;
  download(storagePath: string): Promise<Uint8Array>;
  recordObject(row: UploadedRow): Promise<void>;
  contentTypeFor(path: string): string;
};

export type SyncFailure = { storagePath: string; error: string };

export type SyncSummary = {
  considered: number;
  uploaded: number;
  /** Recorded but not uploaded. Reserved for a future content check. */
  skipped: number;
  bytes: number;
  failures: SyncFailure[];
  /** True when the run stopped because it hit its bite size, not because it
   *  ran out of work. The schedule catches up; this is not a problem. */
  moreWaiting: boolean;
};

/** Netlify gives a synchronous function 60 seconds. This is the bite. */
export const DEFAULT_LIMIT = 200;

/**
 * Where an object lands in the destination.
 *
 * Deterministic, and derived only from the source path, so a re-run computes
 * the same key and re-writing the same bytes is free and idempotent. That is
 * the whole reason this never needs to list or diff the destination -- the
 * expensive and dangerous operations stay unimplemented.
 *
 * The leading segment is stripped of anything that could climb out of the
 * backup folder. A storage path is generated by our own code today, but a
 * path that escapes its prefix is the kind of thing that only becomes
 * reachable later, and a backup writing outside its own folder is a bad way
 * to find that out.
 */
export function remotePathFor(storagePath: string): string {
  const cleaned = storagePath
    .split("/")
    .map((seg) => seg.trim())
    .filter((seg) => seg.length > 0 && seg !== "." && seg !== "..")
    .join("/");
  if (!cleaned) throw new Error(`remotePathFor: nothing usable in ${JSON.stringify(storagePath)}`);
  return `driver-proof/${cleaned}`;
}

/**
 * One pass. Copies what has no backup, records what it copied, and reports
 * what it could not.
 *
 * Never throws for a single object. It throws only if something structural is
 * wrong -- listing fails, or the transport itself is unusable -- because that
 * is the difference between "one photograph did not copy" and "the backup is
 * not running", and those two must not look the same to the caller.
 */
export async function syncOnce(
  deps: SyncDeps,
  opts: { limit?: number } = {},
): Promise<SyncSummary> {
  const limit = Math.max(1, opts.limit ?? DEFAULT_LIMIT);

  // One extra, purely to answer "is there more after this bite" without a
  // second count query. The extra is never uploaded.
  const found = await deps.listPending(limit + 1);
  const moreWaiting = found.length > limit;
  const pending = found.slice(0, limit);

  const summary: SyncSummary = {
    considered: pending.length,
    uploaded: 0,
    skipped: 0,
    bytes: 0,
    failures: [],
    moreWaiting,
  };

  for (const obj of pending) {
    try {
      const remotePath = remotePathFor(obj.storagePath);
      const bytes = await deps.download(obj.storagePath);
      if (bytes.length === 0) {
        // A zero-byte object is not a photograph. Recording it as backed up
        // would mean the real one never gets picked up again.
        summary.failures.push({
          storagePath: obj.storagePath,
          error: "the source object is zero bytes, so there is nothing to back up",
        });
        continue;
      }
      await deps.transport.put(remotePath, bytes, deps.contentTypeFor(obj.storagePath));
      await deps.recordObject({
        storagePath: obj.storagePath,
        sha256: obj.sha256,
        bytes: bytes.length,
        remotePath,
        destination: deps.transport.name,
      });
      summary.uploaded += 1;
      summary.bytes += bytes.length;
    } catch (e) {
      // Recorded and carried on. The row is NOT written, so the next run
      // retries this object without anyone doing anything.
      summary.failures.push({
        storagePath: obj.storagePath,
        error: e instanceof Error ? e.message : String(e),
      });
    }
  }

  return summary;
}

/**
 * How the run is graded.
 *
 * Split out from syncOnce so the rule is one readable expression rather than
 * a condition buried in a loop, and so the script can assert it directly.
 *
 * Hitting the bite size is NOT a failure. Nothing to do is NOT a failure --
 * it is the normal state of a week where no deliveries were photographed,
 * which is most weeks right now. Only an object that should have copied and
 * did not marks the run failed, because that is the only one a person needs
 * to look at.
 */
export function gradeRun(summary: SyncSummary): { status: "ok" | "failed"; error: string | null } {
  if (summary.failures.length === 0) return { status: "ok", error: null };
  const first = summary.failures[0];
  const more = summary.failures.length - 1;
  return {
    status: "failed",
    error:
      `${summary.failures.length} of ${summary.considered} objects did not copy. ` +
      `First: ${first.storagePath} -- ${first.error}` +
      (more > 0 ? ` (and ${more} more)` : ""),
  };
}

/**
 * The staleness alarm, as a sentence rather than a number.
 *
 * @Fred's design point, and the reason this exists at all: "The secret on
 * this app expires and when it does the backup silently stops - same way
 * TriggerForecastRefreshADF died." Four of the eight app registrations in
 * Jesse's tenant already have expired secrets.
 *
 * A backup that has stopped and a backup with nothing to do look identical
 * from the outside. The only thing that separates them is whether an attempt
 * was RECORDED, which is why backup_runs is written at the start of a run and
 * not the end.
 */
export const STALE_AFTER_HOURS = 8 * 24; // weekly schedule, plus a week of slack

export function stalenessVerdict(hoursSinceLastOk: number | null): {
  stale: boolean;
  says: string;
} {
  if (hoursSinceLastOk == null) {
    return {
      stale: true,
      says: "No backup has ever completed successfully. Nothing is copied anywhere.",
    };
  }
  if (hoursSinceLastOk > STALE_AFTER_HOURS) {
    // Two sentences, not one. Floored whole days against a whole-day limit
    // reads as a contradiction at the boundary -- "8 days ago, past the 8 day
    // limit" is the first thing a person sees at six in the morning, and it
    // should not make them squint.
    return {
      stale: true,
      says:
        `The last successful backup was ${(hoursSinceLastOk / 24).toFixed(1)} days ago. ` +
        `The limit is ${STALE_AFTER_HOURS / 24} days. ` +
        `Check the credential first: an expired secret stops this silently.`,
    };
  }
  const days = Math.floor(hoursSinceLastOk / 24);
  return {
    stale: false,
    says: days === 0
      ? "Last successful backup was today."
      : `Last successful backup was ${days} day${days === 1 ? "" : "s"} ago.`,
  };
}
